// index
export const GET_ADVERTISEMENT_LIST = 'GET_ADVERTISEMENT_LIST'
export const GET_DAILY_PROJECTS_LIST = 'GET_DAILY_PROJECTS_LIST'
export const GET_HOT_PROJECTS_LIST = 'GET_HOT_PROJECTS_LIST'
export const GET_AUTHENTICATED_USERS_LIST = 'GET_AUTHENTICATED_USERS_LIST'
export const GET_RECOMMENDED_INVESTORS_LIST = 'GET_RECOMMENDED_INVESTORS_LIST'

// app
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const SET_LOGOUT = 'SET_LOGOUT'
export const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA'
export const SET_AUTO_LOGIN = 'SET_AUTO_LOGIN'