// index
export const GET_ADVERTISEMENT_LIST = 'GET_ADVERTISEMENT_LIST'
export const GET_DAILY_PROJECTS_LIST = 'GET_DAILY_PROJECTS_LIST'
export const GET_HOT_PROJECTS_LIST = 'GET_HOT_PROJECTS_LIST'
export const GET_AUTHENTICATED_USERS_LIST = 'GET_AUTHENTICATED_USERS_LIST'
export const GET_RECOMMENDED_INVESTORS_LIST = 'GET_RECOMMENDED_INVESTORS_LIST'

// app
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const SET_LOGOUT = 'SET_LOGOUT'
export const GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA'
export const SET_AUTO_LOGIN = 'SET_AUTO_LOGIN'
export const SET_RECENT_MOBILE = 'SET_RECENT_MOBILE'
export const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX'
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS'

// discovery
export const GET_ROUND_LIST = 'GET_ROUND_LIST'
export const GET_INDUSTRY_LIST = 'GET_INDUSTRY_LIST'
export const GET_AREA_LIST = 'GET_AREA_LIST'
export const GET_PROJECTS_LIST = 'GET_PROJECTS_LIST'
export const GET_INVESTORS_LIST = 'GET_INVESTORS_LIST'
export const CLEAR_PROJECTS_LIST = 'CLEAR_PROJECTS_LIST'
export const GET_TAGS_LIST = 'GET_TAGS_LIST'
export const GET_USER_TAGS = 'GET_USER_TAGS'

// project
export const GET_PROJECT_DETAIL = 'GET_PROJECT_DETAIL'
export const CLEAR_PROJECT_DETAIL = 'CLEAR_PROJECT_DETAIL'
export const SET_MORE_DETAIL_INFOS = 'SET_MORE_DETAIL_INFOS'
export const GET_SIMILAR_PROJECTS = 'GET_SIMILAR_PROJECTS'
export const CHANGE_COLLECT_STATUS = 'CHANGE_COLLECT_STATUS'

// investor
export const GET_INVESTOR_DETAIL = 'GET_INVESTOR_DETAIL'
export const CLEAR_INVESTOR_DETAIL = 'CLEAR_INVESTOR_DETAIL'
export const GET_INVESTMENT_CASES = 'GET_INVESTMENT_CASES'

// user 
export const GET_INFORMATION_LIST = 'GET_INFORMATION_LIST'